name: CI - Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.0"
          channel: "stable"

      - name: Install Flutter dependencies
        run: |
          flutter pub get

      - name: Build AAB
        run: |
          flutter build appbundle -t "lib/main.dart" --release

      - uses: actions/upload-artifact@v3
        with:
          name: app-release.aab
          path: build/app/outputs/bundle/release/app-release.aab

      - name: Get Version
        id: get_version
        run: echo version="$(grep -m1 '^version:' pubspec.yaml | awk '{print $2}' | sed 's/[[:space:]]//g')" >> $GITHUB_OUTPUT

      - name: Generate Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/bundle/release/*"
          tag: v${{ steps.get_version.outputs.version }}
          token: ${{ secrets.TOKEN }}
