name: Build and deploy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: "11"

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.0"
          channel: "stable"

      - name: Version flutter
        run: |
          flutter --version

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build APK
        run: |
          flutter build appbundle

#          flutter build appbundle --release

#      - name: Generate Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/bundle/release/*"
#          tag: v${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}
