name: CD - Android

on:
  push:
    tags:
      - v*
      - "!v*-*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/download-artifact@v3
        with:
          name: appbundle
          path: build/app/outputs/bundle/release/
          
      - name: Verificar archivo o carpeta
        run: |
          if [ -f "build/app/outputs/bundle/release/app-release.aab" ]; then
            echo "Es un archivo"
          elif [ -d "ruta/al/elemento" ]; then
            echo "Es una carpeta"
