name: Verificar Pull Request

on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "11"
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.0"
          channel: "stable"
          
      - name: Install Flutter dependencies
        run: |
          flutter pub get
          
      - name: Update KeyStore password in gradle properties
        run: |
          sed -i 's/#{SIGNING_STORE_PASSWORD}#/${{ secrets.SIGNING_STORE_PASSWORD }}/g' android/key.properties

      - name: Update KeyStore key password in gradle properties
        run: |
          sed -i 's/#{SIGNING_KEY_PASSWORD}#/${{ secrets.SIGNING_KEY_PASSWORD }}/g' android/key.properties
          
      - name: Build APK
        run: |
          flutter build apk -t "lib/main_prod.dart" --release
      
 
